name: Bug报告
description: Create a report to help us improve
title: "[Bug] <title>"
labels: ["bug"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: |
        在提交之前, 请确认 Please verify that you've followed these steps.
      options:
        - label: 如果你可以自己 debug 并解决的话, 建议您直接提交 PR 或 描述解决方法, 非常感谢!
          required: False
        - label: 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
          required: true
        - label: 我已经使用 最新源码 测试过，问题依旧存在
          required: true
        - label: 这是 QianDao 框架存在的问题，并非我所使用的 QianDao早期版本（如 20210628及之前版号 等）或模板的特定问题
          required: true
        - label: 我提交的不是无意义的 催促更新或修复 请求
          required: true
  - type: input
    id: version
    attributes:
      label: QianDao Version
      description: |
        QianDao 版本号
      placeholder: "20211217"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Bug on OS
      description: |
        发现问题所在的系统环境
      multiple: true
      options:
        - All platform
        - macOS
        - Windows
        - Linux
        - OpenBSD/FreeBSD
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Bug on Platform
      description: |
        发现问题所在的平台
      multiple: true
      options:
        - Docker/macOS
        - Docker/Windows x86
        - Docker/Windows x64
        - Docker/Linux 32位
        - Docker/Linux 64位
        - Code Build/macOS
        - Code Build/Windows x86
        - Code Build/Windows x64
        - Code Build/Linux 32位
        - Code Build/Linux 64位
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        复现此Bug的步骤.
    validations:
      required: true
  - type: textarea
    id: describe_bug
    attributes:
      label: Describe the Bug
      description: |
        对Bug本身清晰而简洁的描述.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      render: shell
      label: QianDao config
      description: |
        在下方附上 QianDao 脱敏后配置文件 或 创建容器命令及环境变量 的内容.
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      render: shell
      label: QianDao log
      description: |
        在下方附上 QianDao后台报错 的日志.
    validations:
      required: true
  - type: textarea
    id: excepted_behavior
    attributes:
      label: Expected behavior
      description: |
        对预期修复后情况的清晰明了的描述.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        添加屏幕截图以帮助解释您的问题.
    validations:
      required: false
