name: Publish Latest Package
on: 
  push:
    paths-ignore: 
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - '**.png'
      - '**.json'
    branches: [master]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Latest Package job
    if: startsWith(github.repository, 'qd-today/qd') # 仓库名

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }} # dockerServer Username 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
        password: ${{ secrets.GITHUB_TOKEN }} # dockerServer Token
    - name: Publish Latest Package
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/386,linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7 # 你准备构建的镜像平台
        push: true
        tags: ghcr.io/qd-today/qd:latest